### ISSUE TITLE
Some errors with PyGLM

### ISSUE THREAD

**Issue by sheiun** [chrystianosaraujo/motion-viewer#1]
After running `motion_viewer_app.py`

```python
Traceback (most recent call last):
  File "motion_viewer_app.py", line 135, in <module>
    app.run()
  File "motion_viewer_app.py", line 43, in run
    self.create_motion_graph(['data/02/02_02.bvh', 'data/02/02_04.bvh'])
  File "motion_viewer_app.py", line 58, in create_motion_graph
    motion.load_from_file(fn)
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 136, in load_from_file
    self._frames.append(process_bvh_rec(frame, bvh_root[0]))
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 129, in process_bvh_rec
    skeleton_node.children.append(process_bvh_rec(frame, child))
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 122, in process_bvh_rec
    skeleton_node._rest_rot = self._compute_rest_rotation(node.estimated_length)
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 348, in _compute_rest_rotation
    return compute_rotation(angle, ortho) #glm.rotate(glm.mat4(), angle, ortho)
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 325, in compute_rotation
    tmp = glm.vec4((1.0 - c) * axis)           
TypeError: invalid argument type(s) for vec4()
```

when print `axis` it shows `vec3` but `vec4` need 4 arguments how do I fix it just add a unit vector for new dimension or change it to `vec3`?

```python
tmp = glm.vec4((1.0 - c) * axis, 1.0)  # is this right
tmp = glm.vec3((1.0 - c) * axis)  # or this
```

My env
```plain
Python 3.6.12
Package       Version
------------- -------------------
certifi       2020.6.20
graphviz      0.14.2
numpy         1.19.2
packaging     20.4
Pillow        7.2.0
pip           20.2.3
PyGLM         1.99.3
PyOpenGL      3.1.5
pyparsing     2.4.7
PyQt5         5.15.1
PyQt5-sip     12.8.1
PyQtWebEngine 5.15.1
pyquaternion  0.9.9
setuptools    50.3.0.post20201006
sip           5.4.0
six           1.15.0
toml          0.10.1
wheel         0.35.1
```

**Comment by sheiun** [comment]
## Indices error

```python
Traceback (most recent call last):
  File "motion_viewer_app.py", line 135, in <module>
    app.run()
  File "motion_viewer_app.py", line 43, in run
    self.create_motion_graph(['data/02/02_02.bvh', 'data/02/02_04.bvh'])
  File "motion_viewer_app.py", line 58, in create_motion_graph
    motion.load_from_file(fn)
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 139, in load_from_file
    self._populate_caches()
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 352, in _populate_caches
    self._populate_positions_cache()
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 387, in _populate_positions_cache
    gather_positions_rec(frame, glm.mat4(1.0))
  File "/home/sheiun/Desktop/motion-viewer/skeleton.py", line 379, in gather_positions_rec
    trans = transform[3, :3]
TypeError: indices must be a pair of integer
```

where `transform` is
```plain
[            1 |            0 |            0 |            0 ]
[            0 |            1 |            0 |            0 ]
[            0 |            0 |            1 |            0 ]
[            0 |            0 |            0 |            1 ]
```
